#! /bin/env julia


#########################################################
# used to extract R matrices for GTRMIX
# https://github.com/RogerLab/GTRPMIX
# code largely generated by DS


#########################################################
using DelimitedFiles


#########################################################
function parse_nexus_model(nexus_content, model_name)
    # Extract the model block
    model_pattern = Regex("model $model_name\\s*=\\s*([\\d\\.\\s\\-]+);", "s")
    model_match = match(model_pattern, nexus_content)
    isnothing(model_match) && error("Model $model_name not found in NEXUS file")
    
    model_data = model_match.captures[1]
    numbers = [parse(Float64, m.match) for m in eachmatch(r"[\d\.\-]+", model_data)]
    
    # The first 190 numbers are the exchangeability matrix (19x20, but upper triangular)
    # The last 20 are the equilibrium frequencies
    exchangeability = zeros(20, 20)
    idx = 1
    
    # Fill the upper triangular part
    for i in 1:20
        for j in i:20
            if i == j
                exchangeability[i,j] = 1.0  # Diagonal should be 1.0
            else
                exchangeability[i,j] = numbers[idx]
                exchangeability[j,i] = numbers[idx]  # Symmetric
                idx += 1
            end
        end
    end
    
    equilibrium_freq = numbers[end-19:end]
    
    return exchangeability[1:19, :], equilibrium_freq
end

function write_prot_matrix(filename, exchangeability, equilibrium_freq)
    open(filename, "w") do io
        # Write exchangeability matrix (first 19 rows)
        writedlm(io, exchangeability, ' ')
        
        # Empty line
        println(io)
        
        # Write equilibrium frequencies
        writedlm(io, transpose(equilibrium_freq), ' ')
    end
end

# Main processing function
function convert_nexus_to_prot(nexus_file, output_prefix)
    nexus_content = read(nexus_file, String)
    
    # Find all model names in the NEXUS file
    model_names = [m.captures[1] for m in eachmatch(r"model\s+(\w+)\s*=", nexus_content)]
    
    for model in model_names
        exchangeability, equilibrium_freq = parse_nexus_model(nexus_content, model)
        output_file = "$output_prefix.$model.dat"
        write_prot_matrix(output_file, exchangeability, equilibrium_freq)
        println("Created $output_file")
    end
end

# Usage example (uncomment to use):
convert_nexus_to_prot("GTR20.nex", "GTR20")


